# Generated by Django 3.1.2 on 2021-05-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Conductor',
            fields=[
                ('Placa', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Placa:')),
                ('Password', models.CharField(max_length=100, verbose_name='Contraseña:')),
            ],
            options={
                'verbose_name': 'Registro de conductor',
                'verbose_name_plural': 'Registro de conductor',
            },
        ),
    ]
